### ISSUE TITLE
Exponent.GLView impl Android issues

### ISSUE THREAD

**Issue by gre** [gre/gl-react#101]
> here is a global issue to track down all the Android issues in current Exponent.GLView implementation.

- if you try to "Debug JS Remotely" it will throw an error, unlike the iOS implementation that "recover" this state. I wish we could eventually actually Debug JS Remotely tho xD

- there is a flash/blink issue. Maybe related to that onDrawFrame gets called even if there is nothing to draw. See for instance example 'blurmapdyn': I have 2+ fbos, only the "final" fbo is supposed to run, but rendering seems to alternate them producing a blink between the normal fbo and the "utility" fbos :o (you can see in following gifs that i randomly have the blur map OR any of the blur pass rendered to the surface..)

![blurmapdyn-blink](https://cloud.githubusercontent.com/assets/211411/25567170/47af178e-2de8-11e7-85bc-fd67f6ac11dd.gif)

- "black transparent" color rendered from a shader does not work as espected (iOS works). See for instance example diamondcrop.

<img width="756" alt="screen shot 2017-04-30 at 21 00 52" src="https://cloud.githubusercontent.com/assets/211411/25567172/4ab714ae-2de8-11e7-820e-80c3bb4ded85.png">

**Comment by stoffern** [comment]
I think it would be better to separate these issues so they are easier to track.

there is a flash/blink issue is related to the Surface renders initial before it applies the values, this happends for every "rerender"..

looking into it now

**Comment by gre** [comment]
agreed. for the flash bug. I wonder if related to https://github.com/expo/expo/issues/538

**Comment by stoffern** [comment]
It is almost impossible to debug or develop a fix on Android as remote debugging is not possible

**Comment by stoffern** [comment]
I have checked the gl-react and the gl-react-native for render cycles and it all renders only once. while when the one render occours it renders twise in the native code.

Native code is not my thing, so i am a little small help there 😞

But you are correct the bug is related to the expo issue

**Comment by gre** [comment]
Cool, at least we know where the problem is. My knowledge of the low level CPP codebase of react-native-webgl is limited as well. I hope more people can help

**Comment by stoffern** [comment]
I wonder why develop 2 sets of WebGL for react-native? why not just make one repo everyone works on and let the exponent guys include that in theyr system. RIght now there are exponents and a port react-native-webgl.. 😉

**Comment by gre** [comment]
That's what I aim for and that's why react-native-webgl is part of that community. I guess the answer is time^^

**Comment by odusseys** [comment]
We are seeing the flashing problem too, it's really annoying.
So far what we've diagnosed is the following
- it really doesn't seem to be related to the javascript code interacting with the native code. We are not animating anything (using threejs) and still getting the jitter. 
- debugging the GPU shows that it is spending a LOT of time on SwapBuffer instructions. 
- the only difference (besides the GL implementation) between the iOS and Android code in RNWebGLView seems to be that 1) the android code adds an option to preserve buffers when swapping and 2) the iOS code has custom drawing logic
I'm wondering if some buffers are not being cleared and the GPU is alternating between several frames.

**Comment by gre** [comment]
i think this no longer happens
