### ISSUE TITLE
[gl-react-expo] app freezes and image isn't rendered

### ISSUE THREAD

**Issue by DaniyarJakupov** [gre/gl-react#118]
#### library version
```
"expo": "^17.0.0",
"gl-react": "^3.6.0",
"gl-react-expo": "^3.6.0"
```

#### Steps to reproduce the behavior
Trying to make work simple example given in README. On IOS Simulator app freezes and image is not rendered. On Android device app is working, but image isn't rendered also.
Here is the code: 
```
import React from 'react';
import { Shaders, Node, GLSL } from 'gl-react';
const shaders = Shaders.create({
  helloBlue: {
    frag: GLSL`
precision highp float;
varying vec2 uv;
uniform float blue;
void main() {
  gl_FragColor = vec4(uv.x, uv.y, blue, 1.0);
}`
  }
});
class HelloBlue extends React.Component {
  render() {
    const { blue } = this.props;
    return <Node shader={shaders.helloBlue} uniforms={{ blue }} />;
  }
}

export default HelloBlue;
```
And 
```
import React, { Component } from 'react';
import { Surface } from 'gl-react-expo';
import HelloBlue from '../components/blue/HelloBlue';

class FeedScreen extends Component {
  render() {
    return (
      <Surface width={300} height={300}>
        <HelloBlue blue={0.5} />
      </Surface>
    );
  }
}

export default FeedScreen;

```

I'm pretty new to react-native, maybe I'm doing smth wrong.

**Comment by Josephmaxim** [comment]
@DaniyarJakupov try changing your render method to this:
```javascript
class FeedScreen extends Component {
  render() {
    return (
      <Surface style={{width: 300, height: 300}}> // Change to style
        <HelloBlue blue={0.5} />
      </Surface>
    );
  }
}

```

**Comment by DaniyarJakupov** [comment]
It works! Thanks man!

**Comment by gre** [comment]
I'm creating an issue that it should display a warning in such case

**Comment by im-hamza-dev** [comment]
> @DaniyarJakupov try changing your render method to this:
> 
> ```js
> class FeedScreen extends Component {
>   render() {
>     return (
>       <Surface style={{width: 300, height: 300}}> // Change to style
>         <HelloBlue blue={0.5} />
>       </Surface>
>     );
>   }
> }
> ```

I got a same problem of image rendering but when I follow the warning to apply props in style, app crashed.

**Comment by farazirfan47** [comment]
same happening with me @im-hamza-dev
