### ISSUE TITLE
[gl-react-native]: <Saturate> seems not firing

### ISSUE THREAD

**Issue by edwardfhsiao** [gre/gl-react#125]
#### library version

![image](https://user-images.githubusercontent.com/11728228/27371295-c83cfcb8-5692-11e7-9536-b53ee6c19c4e.png)

#### Expected behavior
Expecting to have this https://gl-react-cookbook.surge.sh/saturation?brightness=0.9&contrast=0.95&saturation=0.9 

#### Actual behavior
shows nothing inside the
``` <Surface width={480} height={300}> ```
and when I add ``` debugger ``` and ``` console.log('ran')```  in the block of code of ``` export const Saturate = ({ contrast, saturation, brightness, children }) => { ```,  it doesn't actually debug or console.

The gl.js is basically a copy of the link above, I changed gl-react-dom to gl-react-native though.

So I am not sure if I did anything incorrectly.
#### Steps to reproduce the behavior
index.js
```js
//index.js
import Example from './gl';
class Photo extends Component {
  constructor(props) {
    ...
  }
      return (
        <View style={styles.body}>
          <Example/>
        </View>
      );
}
```
gl.js
```js
//gl.js
import React, { Component } from 'react';
import { Shaders, Node, GLSL } from 'gl-react';
import { Surface } from 'gl-react-native';

const shaders = Shaders.create({
  Saturate: {
    frag: GLSL`
    precision highp float;
    varying vec2 uv;
    uniform sampler2D t;
    uniform float contrast, saturation, brightness;
    const vec3 L = vec3(0.2125, 0.7154, 0.0721);
    void main() {
      vec4 c = texture2D(t, uv);
      vec3 brt = c.rgb * brightness;
      gl_FragColor = vec4(mix(
      vec3(0.5),
      mix(vec3(dot(brt, L)), brt, saturation),
      contrast), c.a);
  }
  `
  }
});

export const Saturate = ({ contrast, saturation, brightness, children }) => {
  //console.log('ran');
  //debugger;  
  return (<Node
    shader={shaders.Saturate}
    uniforms={{ contrast, saturation, brightness, t: children }}
  />
)};

export default class Example extends Component {
  render() {
    return (
      <Surface width={480} height={300}>
        <Saturate {...this.props}>
          https://i.imgur.com/uTP9Xfr.jpg
        </Saturate>
      </Surface>
    );
  }
  static defaultProps = {
    contrast: 1,
    saturation: 1,
    brightness: 1
  };
}
```
![image](https://user-images.githubusercontent.com/11728228/27371346-fbbe81ce-5692-11e7-94ae-3137af484352.png)

**Comment by Josephmaxim** [comment]
@edwardfhsiao 
change `<Surface width={480} height={300}>` to `<Surface style={{width: 480, height:300}}>` 
Ref: [Issue #118](https://github.com/gre/gl-react/issues/118)

**Comment by edwardfhsiao** [comment]
@Josephmaxim Well, I changed to
```js
export default class extends Component {
  render() {
    return (
      <Surface style={{width: 480, height:300, borderColor:'#ff0000', borderWidth: 1}}>
        <Saturate {...this.props}>
          https://i.imgur.com/uTP9Xfr.jpg
        </Saturate>
      </Surface>
    );
  }
}
```

yet it still not rendering

![image](https://user-images.githubusercontent.com/11728228/27463174-8297ae4e-57f8-11e7-83bf-33e2ac4556fe.png)

**Comment by Josephmaxim** [comment]
@edwardfhsiao Turn off remote debugger. that should fix it.

**Comment by edwardfhsiao** [comment]
@Josephmaxim not really :(

**Comment by Josephmaxim** [comment]
@edwardfhsiao any specific errors?

**Comment by edwardfhsiao** [comment]
@Josephmaxim Unfortunately, there is no error showing

**Comment by Josephmaxim** [comment]
@edwardfhsiao change the uri from `https://i.imgur.com/uTP9Xfr.jpg` to `{{uri:"https://i.imgur.com/uTP9Xfr.jpg"}}`

**Comment by edwardfhsiao** [comment]
@Josephmaxim nope, I have also tried dynamic local image, nothing happened

**Comment by edwardfhsiao** [comment]
@Josephmaxim I think the key here is 
```js
export const Saturate = ({ contrast, saturation, brightness, children }) => {
  console.log('ran');
  return (<Node
    shader={shaders.Saturate}
    uniforms={{ contrast, saturation, brightness, t: children }}
  />
)};
```
it does not console out at all

**Comment by Josephmaxim** [comment]
@edwardfhsiao  this one works for me
```javascript
import React, { Component } from 'react';
import { Shaders, Node, GLSL } from 'gl-react';
import { Surface } from 'gl-react-native';

const shaders = Shaders.create({
    Saturate: {
        frag: GLSL`
    precision highp float;
    varying vec2 uv;
    uniform sampler2D t;
    uniform float contrast, saturation, brightness;
    const vec3 L = vec3(0.2125, 0.7154, 0.0721);
    void main() {
      vec4 c = texture2D(t, uv);
      vec3 brt = c.rgb * brightness;
      gl_FragColor = vec4(mix(
      vec3(0.5),
      mix(vec3(dot(brt, L)), brt, saturation),
      contrast), c.a);
  }
  `
    }
});

export const Saturate = ({ contrast, saturation, brightness, children }) => {
    //console.log('ran');
    //debugger;
    return (<Node
            shader={shaders.Saturate}
            uniforms={{ contrast, saturation, brightness, t: children }}
        />
    )};

export default class Example extends Component {
    render() {
        return (
            <Surface style={{width: 480, height:300, borderColor:'#ff0000', borderWidth: 1}}>
                <Saturate {...this.props}>
                    {{uri:"https://i.imgur.com/uTP9Xfr.jpg"}}
                </Saturate>
            </Surface>
        );
    }
    static defaultProps = {
        contrast: 6,
        saturation: 1,
        brightness: 1
    };
}
```
<img width="413" alt="screen shot 2017-06-23 at 2 44 52 am" src="https://user-images.githubusercontent.com/10732770/27469519-f853ebb0-57bd-11e7-8a34-4cd83a9eecd7.png">

**Comment by edwardfhsiao** [comment]
@Josephmaxim may I know your react-native version?

**Comment by Josephmaxim** [comment]
@edwardfhsiao remote debugging doesn't work with gl-react-native not sure why though.
you should get this error on console `EXGL: Can only run on JavaScriptCore! Do you have 'Remote Debugging' enabled in your app's Developer Menu (https://facebook.github.io/react-native/docs/debugging.html)? EXGL is not supported while using Remote Debugging, you will need to disable it to use EXGL.`

**Comment by Josephmaxim** [comment]
@edwardfhsiao 
```javascript
"dependencies": {
    "gl-react": "^3.6.0",
    "gl-react-native": "^3.6.0",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-image-resizer": "^0.1.1",
  },
```

**Comment by edwardfhsiao** [comment]
@Josephmaxim I found the issue! My RNGL.xcodeproj did not set up correctly. Thanks for the help man, sorry that I bothered you for so long.

**Comment by gre** [comment]
yeah, I'm afraid debugging won't work like in the EXGLView implementation. as in WebGL spec, the gl calls needs to exec in sync, so we need to actively "block" the JS somehow. EXGLView impl expect the JS to run in JavascriptCore (because the gl.* method directly exec some C++ code with low overhead) but this can't work inside Chrome (the remote debugging means executing the JS in Chrome instead of JSC).

I hope this was more documented in EXGLView  and in gl-react-native README (or somewhere!) , feel free to send PR to improve that.


also @nikki93 can probably comment more on the technical reason of this choice ;)
