### ISSUE TITLE
No Podfile?

### ISSUE THREAD

**Issue by aaronbuchanan** [gre/gl-react#126]
It looks like the v2.* repo [supported cocoapods](https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/RNGL.podspec), but this repo doesn't have a podspec. Was a decision made to not support installing v3.* via cocoapods? Is this documented anywhere? 

For more context, we found that in order to get `react-native-maps` running with the `GOOGLE_PROVIDER` on ios, we had to move our `React` library into cocoapods. 

After following install instructions, I get this error:  
```
/node_modules/gl-react-native/ios/EXGLViewManager.h:1:9: 'RCTViewManager.h' file not found
```

AFAIK when I [bring in React via cocoapods](https://gist.github.com/aaronbuchanan/920d61364fd884de1a67a9965805a737), any libraries that depend on react need to be pods. (appreciate anyone letting me know if this is wrong, as I haven't been able to get any react-native link stuff to find react when building)

Thanks!

**Comment by gre** [comment]
we can add that yeah, probably valid use case. it would be great if we could create a minimal new app in a `packages` that would use this paradigm (cocoapods) to check it works correctly

**Comment by gre** [comment]
the error you mentioned has been fixed. is there still a need for a Podfile?

**Comment by gre** [comment]
oh yeah I guess when you have React as pod dep.

I will need to figure out how I can bring that into Podfile, but first need to migrate the latest EXGLView (that have a dep to GPUImage lib)

**Comment by gre** [comment]
one "trick" to do in that Podfile is to dynamically load the version so i don't have to maintain it, like in  https://github.com/gre/react-native-view-shot/blob/master/RNViewShot.podspec#L2

**Comment by aelam** [comment]
The GLES part should be  independent without ReactNative. 
and the ReactNative wrapper can have a ReactNative dependency 

The structure in my head is like this 
 - gl-react
    -  GLES React Native Wrapper   // subspec
        -  GLES OOP wrapper             // subspec

Then it can be used with or without ReactNative

**Comment by gre** [comment]
what do you mean by GLES OOP ? the core implementation is EXGL.cpp (which comes from https://github.com/expo/expo/blob/master/cpp/UEXGL.cpp ) that basically implement the webgl context api with JavaScriptCore, it have a dependency on JavaScriptCore but it not depends on ReactNative. then some iOS / Android code will use it and instanciate it.

**Comment by gre** [comment]
the library no longer need a podfile because there is no longer any native code. now is delegated to lib `react-native-webgl`
