### ISSUE TITLE
How to install this repo?

### ISSUE THREAD

**Issue by ebhoren** [gre/gl-react#141]
How to i install this repo from NPM?

**Comment by gre** [comment]
I need to clarify these in the README.

this hosts the alpha v3 of gl-react, it depends which implementation you want but basically gl-react, gl-react-native, gl-react-dom are all available on NPM, for the v3 you need either to use the tagged `@next` or can use `3.x`

see for instance the web cookbook: https://github.com/gre/gl-react/blob/master/packages/cookbook/package.json#L13-L14

**Comment by ebhoren** [comment]
Thanks you so much :)

**Comment by OKNoah** [comment]
This was slightly confusing because there's multiple repos from multiple parties, so I assumed different npm packages as well.
