### ISSUE TITLE
gl-react website is down

### ISSUE THREAD

**Issue by fisch0920** [gre/gl-react#142]
When visiting [https://gl-react-cookbook.surge.sh/](https://gl-react-cookbook.surge.sh/) in latest Chrome browser on Mac OS, the page fails to load with a JS error from a minified script:

```
Uncaught TypeError: g.join is not a function
    at n.r (html-block.js:40)
    at n.t [as tokenizeBlock] (tokenizer.js:111)
    at n.r [as parse] (parse.js:41)
    at Function.a [as parse] (index.js:275)
    at r (index.js:22)
    at n (index.js:93)
    at e (index.js:56)
    at Object.e [as run] (index.js:30)
    at o (index.js:371)
    at S (index.js:366)
```

The site has been very useful thus far and is a great source of documentation.  Hope this gets resolved soon -- thanks!

**Comment by gre** [comment]
it should be back shortly. https://github.com/gre/gl-react/commit/d19dfe55b26631a1e54ca8475fa6ae02c5944544

it was affected by a breaking regression in webpack json-loader which was breaking the lib "remark" at runtime.. I might reconsider the fact the cookbook gets auto redeployed for each master commit.. actually if you have an idea how I could test that the app don't crash at runtime from Travis (like just test that "/" don't throw an exception after a second) I would be happy to add that check

**Comment by fisch0920** [comment]
Thanks @gre 

I know it's possible to add this type of check, but it's not a trivial addition.
