### ISSUE TITLE
Android & 0.47

### ISSUE THREAD

**Issue by kelset** [gre/gl-react#146]
### *bug report*

(tbh it's more of an headsup, I know the new version just rolled out yesterday so no rush)

Maybe related to #133 or #131?

#### library version

```bash
├── gl-react@3.9.0
└── gl-react-native@3.9.0
```

#### Expected behaviour

To get `react-native run-android` to build the apk.

#### Actual behavior

Get this error:

```bash
:RNGL:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/kelset/Developer/ETV/the-week-react/node_modules/gl-react-native/android/src/main/java/fr/greweb/rngl/RNGLPackage.java:23: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /.../node_modules/gl-react-native/android/src/main/java/fr/greweb/rngl/GLImagesModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /.../node_modules/gl-react-native/android/src/main/java/fr/greweb/rngl/EXGLViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:RNGL:compileReleaseJavaWithJavac FAILED
```

#### Steps to reproduce the behaviour

Update to `react-native v0.47` and run command `react-native run-android`.

--
Edit: I think the fix should be quite easy - by looking at [another lib](https://github.com/rebeccahughes/react-native-device-info/commit/1dd6234d4b511575842bfa7f052f0777ebb21f53).

**Comment by gre** [comment]
@kelset i think that might just be the same fix than in https://github.com/gre/react-native-view-shot/pull/78 – I can accept PR and quickly release a new version

**Comment by kelset** [comment]
;)
#149

**Comment by kelset** [comment]
Btw, actually, I'm having an issue with iOS too (sorry didn't test at the time of submitting the issue) - I get this error from the lib:

`EXGLView.m:7:9: fatal error: 'React/RCTBridge+JavaScriptCore.h' file not found
#import <React/RCTBridge+JavaScriptCore.h>`

**Comment by gre** [comment]
that iOS error is related to 0.47 too?

**Comment by kelset** [comment]
Yeah.

**Comment by gre** [comment]
yeah I think let's create a new issue. i hope this is easy to solve, I wonder where `RCTBridge+JavaScriptCore.h` have moved and how we can migrate current code (i don't think Expo have yet addressed that, they usually are a bit behind RN releases)

**Comment by gre** [comment]
related https://github.com/facebook/react-native/commit/c143313a20eab73e224fbb495e3d139ce8e507a0
