### ISSUE TITLE
Question - Is it possible to detect when the content of the Surface have loaded?

### ISSUE THREAD

**Issue by serhiipalash** [gre/gl-react#159]
### *feature request*? 

I want to take the snapshot of the loaded Surface, but `onLoad` event fires early then all content have loaded. Do you have any idea how to handle this?

#### library version

<img width="502" alt="screen shot 2017-09-14 at 17 38 41" src="https://user-images.githubusercontent.com/14208343/30435931-a876efc8-9973-11e7-99d2-59afbff0edea.png">

#### Expected behavior

<img width="1280" alt="screen shot 2017-09-14 at 17 42 12" src="https://user-images.githubusercontent.com/14208343/30436130-1be2b3fc-9974-11e7-8527-e02a302eba57.png">

#### Actual behavior

<img width="1280" alt="screen shot 2017-09-14 at 17 39 47" src="https://user-images.githubusercontent.com/14208343/30435952-bc64a25a-9973-11e7-8da4-01a120eaadf8.png">

#### Steps to reproduce the behavior

Clone this repo and open in Expo XDE

https://github.com/serhiipalash/opengl-test

**Comment by gre** [comment]
by default, the Surface will render as soon as possible and won't wait images, if an image is not loaded yet, it renders black instead.

To have a different behavior, you need to specify the images to wait in a `preload` prop.
it will force Surface to wait for all images to render the first frame AND should only trigger onLoad after that.


example
```
<Surface preload={[ image1, image2 ]} onLoad={this.onLoad} ...>
  <Node ... uniforms={{ t1: image1, t2: image2 }} />
</Surface>
```

(the preload array contains same format as you would pass to uniform texture)

**Comment by serhiipalash** [comment]
Thank you for your help @gre !
