### ISSUE TITLE
The width of the surface isn't getting on the screen

### ISSUE THREAD

**Issue by SvetoslavSlavov** [gre/gl-react#161]
![simulator screen shot oct 2 2017 5 57 30 pm](https://user-images.githubusercontent.com/16868443/31117252-db4aaed6-a831-11e7-9535-5a425c0e6927.png) 
I am getting this. The code is 
```
state = {
        path: "https://i.imgur.com/uTP9Xfr.jpg",
        contrast: 1,
        brightness: 1,
        saturation: 1
    }
```
` const { width, height, brightness, contrast, saturation } = this.state;`

       const filter = {
            brightness,
            contrast,
            saturation
        }
` <Surface style={{ width: 800, height: 800 }}>
         <Saturate {...filter}>
                  {{ uri: this.state.path }}
          </Saturate>
    </Surface>`

**Comment by gre** [comment]
which version of gl-react are you using?
sounds like you use the v2 with code that only works with the v3, but i might be wrong.
also do you get any warnings?

**Comment by stoffern** [comment]
@SvetoslavSlavov ...

**Comment by JBriggs666** [comment]
Did you manage to get this working or is it a bug? 

I'm having exactly the same problem using gl-react@3.13.0 & gl-react-native@3.13.0 but I am also only a couple of days into playing with react-native so I could have just done something a bit daft.

![simulator screen shot - iphone 6 - 2017-11-02 at 21 23 46](https://user-images.githubusercontent.com/10177759/32351304-cfc70910-c014-11e7-86f7-afda144e3f37.png)

The Code

```
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';
import { Surface } from 'gl-react-native';
import Saturate from './Saturation';

export default class App extends Component<{}> {
  render() {

    const filter = {
      contrast: 1,
      saturation: 1,
      brightness: 1
    }

    return (
      <View>
        <Surface style={{ width: 480, height: 300 }}>
          <Saturate {...filter}>
            {{ uri: "https://i.imgur.com/uTP9Xfr.jpg" }}
          </Saturate>
        </Surface>
      </View>
      );
  }
}
```

**Comment by gre** [comment]
This bug means that your project don't have react-native-webgl correctly compiled and linked. Make sure that libRNWebGL (or something like that) is present in the linked libs.
Please refer to react-native-webgl readme
