### ISSUE TITLE
Error compiling shader

### ISSUE THREAD

**Issue by stoffern** [gre/gl-react#163]
Android

Error:
`gl-shader: Error compiling shader: 0:8: S0012: Global variable initializer must be a constant expression`

Code is:
```js
import { Surface } from "gl-react-native";
import GLImage from "gl-react-image"

<Surface style={{width: 100, height: 200}}>
  <GLImage
    source={{uri: "https://i.imgur.com/2VP5osy.jpg"}}
    resizeMode="cover"
  />
</Surface>
```

**Comment by gre** [comment]
looks like it's a bug in gl-react-image ?

**Comment by stoffern** [comment]
Yes, this is quite wierd. Have been looking at it for "24 hours"

Works in Android simulator but not on device.
Running a normal shader with static values works fine.

**Comment by gre** [comment]
I highly suspect this is because of this guy, https://github.com/gre/gl-react-image/blob/master/src/index.js#L45

maybe worth trying to inline the calc each time `r` was used

**Comment by stoffern** [comment]
I can try to remove the "free" shader and see if that works first.

**Comment by gre** [comment]
shader are only compiled if they are used so I doubt this will do it. also this pattern is used in contain and cover too, just try to move the `float r = res.x / res.y;` into the `main()`

**Comment by gre** [comment]
I think the bug is because the device must have a different version of OpenGL or something like that –_–

**Comment by stoffern** [comment]
ah, okey. Well moving the `float r` line into `main()` did not work

**Comment by gre** [comment]
mmh weird. because this error really makes me thing it's a global variable glsl thing, and `float r` is the only case in gl-react-image shader mmh (like in this fix https://github.com/yorung/AdamasFramework/commit/f9b75693f1eacd1bd5a6a2d192b020aacadde095 )

**Comment by stoffern** [comment]
If it is a global variable thing and it works on older version of OpenGL a workaround could be to test a 
`<uses-feature android:glEsVersion="0x00020000" android:required="true" />`
in the manifest?

**Comment by stoffern** [comment]
> **Additions to the OpenGL ES Shading Language 3.20 Specification**
> 
> "In declarations of global variables with no storage qualifier or
>     with a const qualifier, any initializer must be a constant expression.
>     Declarations of global variables with other storage qualifiers may not
>     contain initializers. Global variables without storage qualifiers that
>     are not initialized in their declaration or by the application will not
>     be initialized by OpenGL ES, but rather will enter main() with undefined
>     values."

Ref: https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_shader_non_constant_global_initializers.txt

**Comment by stoffern** [comment]
@gre my newbie mistake i changed the `src/` and not the `lib/` in `node_modules`

Moving the `float r` into main works. I think that declaration outside and done inside `main()` is best :) i will make a PR on it for `gl-react-image`

Tested and works on OpenGL 2 & 3.2 😉
