### ISSUE TITLE
How to render multiple game sprites with react-gl shaders applied.

### ISSUE THREAD

**Issue by funkjunky** [gre/gl-react#164]
### *feature request* / *Question*

So, how would I create a game with multiple sprites using this?

Would I have multiple <Surface> elements?
Or would I have one Surface element, and multiple Surface elements inside that surface element?
Can I nest Surface elements?

How would I use this to have say 10 sprites, with their own shaders, and perhaps a shader that applies to all of the sprites. I'd imagine something like:

main:
```
    <Surface>
         <MyGlobalShader>
             <Sprite />
              </Spite />
         </MyGlobalShader>
    </Surface>
```

Sprite:
```
    <Sprite>
        <MySpriteShader>
             <JSON2D ... />
        </MySpriteShader>
    </Sprite>
```

My experience with shaders is limited, and I've yet to actually use gl-react, I'm simply evaluating things. I want to do cross platform game dev with react, but so far the furthest ive done is react-pixi-redux web game dev.

**Comment by gre** [comment]
it's probably beyond scope of this library. the library just provide basic blocks that allow you to write fragment shaders. i guess you would need to access vertex shader to do this. you probably would be interested to look directly at pixi library
