### ISSUE TITLE
RN 0.50 bundler bug for iOS

### ISSUE THREAD

**Issue by kelset** [gre/gl-react#165]
#### library version
```bash
├── gl-react@3.13.0
└── gl-react-native@3.13.0
└── react-native-webgl@kelset/react-native-webgl#patch-2
```
#### Expected behavior

To bundle fine with iOS and Android, while using `react-native` 0.50.3.

#### Actual behavior

While Android works fine, in iOS I get this error from bundler:

```js
error: bundling failed: UnableToResolveError: Unable to resolve module `react-native-webgl` from `<APP_PATH>/node_modules/gl-react-native/lib/GLViewNative.js`: Module does not exist in the module map or in these directories:
  <APP_PATH>/node_modules
```

I think it may be related to the [BC related](https://github.com/facebook/react-native/releases/tag/v0.50.0) to "Default enableBabelRCLookup (recursive) to false".

When I reverse to rn 0.49.5 I don't have this issue. (I'm using my branch simply because there's no a new release of webgl with the merged PR yet)

**Comment by gre** [comment]
i can run the library against latest RN, is there something i'm missing? 🤔

**Comment by kelset** [comment]
Don't know now tbh, it's been quite a while and at my new job we don't use `gl-react` - I'll close this.
