### ISSUE TITLE
gl-react and server side rendering with Next.js

### ISSUE THREAD

**Issue by charlesvinette** [gre/gl-react#166]
#### library version

```bash
gl-react@3.13.0 
```

#### Expected behavior
Copying the Gist should render the same image as what is shown in the README.
#### Actual behavior
Nothing is being rendered, but I see the Frame of the canvas in the inspector
#### Steps to reproduce the behavior
Init a new Next.js project and try to replicate the example from the README.

#### Details

Hello! First of all thank you very much for your hard work on this library, it is amazing.

I am building a website using Next.js and I am trying to add a Shader to an image. From what I understand, I need to use `gl-react-headless` for server side rendering. However, when I try to replicate the very simple example that is included in the README, nothing is being rendered. It is my first time using shaders so I might very well do something wrong, I apologize in advance!

Have a great day

**Comment by gre** [comment]
I can try to give a look asap

**Comment by charlesvinette** [comment]
Hey @gre! Thank you, let me know if I can be of any help. I switched to CRA for the Website and it worked instantly with `gl-react-dom`.

**Comment by gre** [comment]
the next version i'll release will have it fixed . bug was https://github.com/gre/gl-react/commit/dab6ded6d0ccff600f7b234e01b8a351fec828f1

**Comment by charlesvinette** [comment]
Hey @gre! Perfect, good job! Once again, thank you for your hard work 👍
