### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by songxiaoliang** [gre/gl-react#167]
Does React Native 0.44.3 support it?

**Comment by gre** [comment]
it should. if not, you can investigate the problem and submit a PR. try to use the latest version, if it breaks at some point, we can figure out how to make it backward compatible (I think it will be in react-native-webgl, gl-react-native no longer have any native code and relies on react-native-webgl)

**Comment by songxiaoliang** [comment]
@gre 
gl-react: 3.13.0
gl-react-native: 3.13.0
react-native-webgl: 0.8.0
react-native: 0.44.3

Running on iOS, the following error appears, looking forward to the author reply as soon as possible

![35546758-92ea10b4-05b0-11e8-8589-e9ad2b08a57d](https://user-images.githubusercontent.com/6975588/35547458-2f9a3062-05b4-11e8-8b31-26dde243061d.jpg)

**Comment by gre** [comment]
I have no idea what this error means. it seem to break in React Native JS execution loop?

**Comment by gre** [comment]
let's continue on https://github.com/react-community/react-native-webgl/issues/42
