### ISSUE TITLE
Invariant Violation: Element

### ISSUE THREAD

**Issue by Angelk90** [gre/gl-react#169]
#### library version

```
    "gl-react": "^2.3.1",
    "gl-react-image": "^0.1.0",
    "gl-react-instagramfilters": "^0.2.0",
    "gl-react-native": "^2.48.0",
```

#### Expected behavior
See the image.

#### Actual behavior
![schermata_2018-02-04-16-32-51-363](https://user-images.githubusercontent.com/20476002/35779179-33a0b848-09c9-11e8-80b6-08f4a1ee8f38.jpeg)

#### Steps to reproduce the behavior
```
import React, { Component } from 'react';
import { PropTypes } from 'prop-types';
import { View, Text, Image } from 'react-native';
import { Surface } from "gl-react-native";
//import {Hudson} from "gl-react-instagramfilters";
import GLImage from "gl-react-image";

export default class App extends Component {
  render() {
    return (
      <Surface height={1024} width={693}>
        <GLImage source="http://i.imgur.com/tCatS2c.jpg" resizeMode="cover" />
      </Surface>
    );
  }
}
```

@gre : What am I doing wrong?

**Comment by gre** [comment]
your issue concerns gl-react v2, this repository is the v3. either create an issue on the v2 repository or move to v3. we are going to release it soon btw https://github.com/gre/gl-react/issues/170
