### ISSUE TITLE
ETA to release

### ISSUE THREAD

**Issue by gre** [gre/gl-react#170]
- need to refactor a bit the project, upgrade deps, use lerna & yarn workspaces
- need to clean up issues and see if there are easy tasks to finish off
- release the v3 !

based on my availability, the release is scheduled for March 1st.

draft notes to put in the release: gl-react is stable. gl-react-native / gl-react-expo is only a light wrapper on top of (react-native-webgl / exgl). it's up to the underlying library to improve the state of the WebGL implementation if there are bugs/performance concerns. there is no more native code in gl-react side

**Comment by superandrew213** [comment]
@gre thank you for all your work on this project!

**Comment by gre** [comment]
should release this weekend :) everyone is busy discussing about awesome Dan's talk today 😄 mindblowing stuff. there will be interesting implication of createFetcher in gl-react :)

**Comment by framerate** [comment]
Thank you @gre! I'm about to start playing with this to power my game engine's 2nd renderer in April... very anxious to start playing and hopefully give back!

Also, if you know any other game developers using this/javascript/react you should hit me up and talk :)

**Comment by gre** [comment]
happy to talk about it. not sure if this library is suitable enough for this usecase tho.

(btw v3 was released in time ;) )
