### ISSUE TITLE
Getting "Invariant Violation: Objects are not valid as a React child" error

### ISSUE THREAD

**Issue by newlifepop** [gre/gl-react#173]
Trying to write some blur effect `exactly` like this:

![screen shot 2018-02-09 at 23 11 15](https://user-images.githubusercontent.com/24434460/36058755-955c794a-0dee-11e8-99b6-b0059c34f7ce.png)

I copied `BlurV` effect from the example folder, then, in my component, I used `BlurV` like this:

    import { Surface } from 'gl-react-native';
    import { BlurV } from '../path/to/BlurV';

    class BlurView extends Component {
        ...
        ...

        render() {
            <Surface style={{ width: 300, height: 200 }}>
                <BlurV map={map} passes={passes} factor={factor}>
                    {{ uri: `data:image/jpg;base64,${photoData}` }}
                </BlurV>
            </Surface>
        }
    }

    export default BlurView;

The line with **{{ uri: `data:image/jpg;base64,${photoData}` }}**, `photoData` is a encoded `base64` string (when I change it to a network photo `https://someurl.com`, I get the same error, therefore, I don't think it's because it a base64 encoded image). I get this error:

![screen shot 2018-02-09 at 23 21 22](https://user-images.githubusercontent.com/24434460/36058815-f5b7bd26-0def-11e8-802e-5a3fc7df4e9e.png)

Why? How can I solve it though?

**Comment by gre** [comment]
I think it's a problem with your gl-react / gl-react-native versions. 

double check with `yarn list gl-react-*` (or `npm ls gl-react-*`) . the v3 was so far an alpha and not published on `latest` tag, so it's likely you installed the v2 accidentally. NB i'll finally release v3 this weekend :)


please see the example https://github.com/gre/gl-react/blob/master/examples/cookbook-rn-shared/examples/blurmap/index.js#L58-L62
I have even tried with a base64 uri and it works

<img width="1065" alt="capture d ecran 2018-03-03 a 13 01 12" src="https://user-images.githubusercontent.com/211411/36934024-24ef6a7c-1ee3-11e8-8452-d122b721df19.png">
