### ISSUE TITLE
How to save into a picture to the local

### ISSUE THREAD

**Issue by songxiaoliang** [gre/gl-react#174]

**Comment by gre** [comment]
if you mean, in context of gl-react-native v3, capture is not yet supported. see the more general issue: https://github.com/gre/gl-react/issues/93

**Comment by songxiaoliang** [comment]
emmm..   I used react-native-iew-shot to crop the gl-react rendering area, but it did not work. Now I need a way to get the gl-react rendered image, but I do not know what to do.

"gl-react": "^3.13.0",
"react-native-view-shot": "^2.3.0",
"gl-react-native": "^3.13.0",

**Comment by songxiaoliang** [comment]
@gre

**Comment by gre** [comment]
`react-native-view-shot` is likely not to work for capturing any GL backed view and will produce different results across platform (I think iOS support it but not Android afaik). sorry but I don't think there is a solution to capture a gl view at the moment in context of gl-react-native v3

**Comment by gre** [comment]
main work is to be done on webgl implementation side (react-native-webgl / expo exgl) to provide this feature. there is nothing i can do easily on gl-react side.

**Comment by songxiaoliang** [comment]
@gre Is there any way to save the gl-react-native rendered image? Looking forward to the author reply

**Comment by songxiaoliang** [comment]
@gre ok， thanks

**Comment by mopilo** [comment]
@gre any update on saving image??
