### ISSUE TITLE
Multiple shaders on same Node

### ISSUE THREAD

**Issue by nuthinking** [gre/gl-react#175]
I posted it on the React Native repo but because it involved the API, this is the best place for it.

How could I apply multiple/independent shaders to the same Node (texture)? Shouldn't perhaps be the property `shader` be `shaders` and accepting an array?

Very impressive project by the way. Thanks!

**Comment by gre** [comment]
so you mean like a pipeline of effect you want to chain? This is done by wrapping components.

for instance

https://gl-react-cookbook.surge.sh/diamondhello

I probably should add an example with even more chaining steps

**Comment by nuthinking** [comment]
@gre oh, this is very interesting. So I guess I could generate such tree dynamically as shaders are removed or added to the view. Will give it a try, thanks a lot!

**Comment by nuthinking** [comment]
I managed to rebuild it. Interesting the texture being the children (which makes sense): https://jsfiddle.net/qg6vc2ob/9/

**Comment by gre** [comment]
yeah, and you can stack then again and again, each Node instance is going to hold a Framebuffer reference, which is drawn when and only when Node is redrawn (react update), allowing to cache part of that tree. See also some advanced examples involving Blur, blur is implemented by nesting many `<Blur1D>` : https://gl-react-cookbook.surge.sh/blurmap?factor=4.4&passes=6

**Comment by nuthinking** [comment]
(@gre sent you more info about what I am trying to build on Twitter.)
