### ISSUE TITLE
[Android] Images in ScrollView gets black flickers

### ISSUE THREAD

**Issue by vignesarul** [gre/gl-react#176]
#### library version
├── gl-react@3.14.0
└── gl-react-native@3.14.0

#### Expected behavior
IOS Screenshot:
![2018-03-05 18 00 37](https://user-images.githubusercontent.com/30304333/36975358-d7424b14-209f-11e8-9251-d9ffe8cc0681.gif)

#### Actual behavior
Android screenshot:
![2018-03-05 18 17 27](https://user-images.githubusercontent.com/30304333/36975874-8db42826-20a1-11e8-842e-552319647536.gif)

#### Steps to reproduce the behavior
1. Create a component like this on react native: https://gl-react-cookbook.surge.sh/helloblue
2. With in react-native's horizontal ScrollView, add few instance of the component created in step 1
3. Swipe the images

**Comment by vignesarul** [comment]
Workaround solution for this issue is, 
1. Render the image within gl-react-native's Surface.
2. Use Surface's **captureFrame** method to capture the frame as base64. https://github.com/gre/gl-react-v2/blob/master/docs/api/Surface.md#captureframeconfig.
3. Use reactnative's Image component to render the base64 image string. Now scroll doesn't produce flickering effect.

**Comment by songxiaoliang** [comment]
@vignesarul How to solve it? I have now loaded 8 filters in the scrollView, but there will always be a black one.

**Comment by vignesarul** [comment]
@songxiaoliang I don't know why you are getting a separate black image.
Rendering surface/canvas from gl-react within react-native's scrollView creates black flickers while swiping. I used surface's captureFrame method to get base64 of filter applied image & render it as a normal image in scrollView.

**Comment by songxiaoliang** [comment]
@vignesarul What's more serious is that it will cause the App to be stuck, page switching will not be smooth, and even a crash will occur. Do you have any good solutions?

**Comment by gre** [comment]
Please check on latest implementation (v4), this should be fixed. if not we can reopen and i would need a minimal reproductible example.

thanks
