### ISSUE TITLE
setState Refresh, black screen

### ISSUE THREAD

**Issue by songxiaoliang** [gre/gl-react#180]
![simulator screen shot - iphone 6 - 2018-04-12 at 12 22 36](https://user-images.githubusercontent.com/6975588/38656313-3dc7089c-3e4c-11e8-8447-76dcc8ea2514.png)
Click on the item below to refresh the above display. There will be a black screen problem. How to solve it?

"gl-react": "^3.13.0",
"gl-react-image": "^3.1.1",
"gl-react-native": "^3.13.0",

**Comment by songxiaoliang** [comment]
@gre Yes, when I click on the sample at the bottom, it will refresh the big picture above, but there will be a black screen, I do not know how to solve?

**Comment by songxiaoliang** [comment]
@gre Need to click several times repeatedly to render

**Comment by gre** [comment]
that sounds like a bug in the texture loader, on the implementation side (react-native-webgl in your case).
i'm not sure how to fix it, need to investigate more

**Comment by dinotrnka** [comment]
I'm having the same problem. Everything works on the iOS simulator, but on the device, it won't refresh properly and I get a black screen.

If I change the state for the second time, it will refresh properly though.

Is there any progress on this?

**Comment by dinotrnka** [comment]
Are there any known workarounds, did this work on earlier versions? I tried a ton of different hacks and nothing seems to work :/

**Comment by songxiaoliang** [comment]
@dinotrnka I don't have a better solution right now.

**Comment by gre** [comment]
Please check on latest implementation (v4), this should be fixed. if not we can reopen and i would need a minimal reproductible example.

thanks
