### ISSUE TITLE
cookbook-expo won't run (750f241)

### ISSUE THREAD

**Issue by codekiln** [gre/gl-react#181]
Running `cookbook-expo` example doesn't work for me locally:

#### Expected behavior: 
`cookbook-expo` demo opens in iOS simulator

#### Actual behavior: 
"Unhandled JS Exception: Unexpected keyword 'import'" (near `node_modules/expo/tools/hashAssetFiles:1403`)
![image](https://user-images.githubusercontent.com/140930/39083909-a5d6312a-453a-11e8-822c-6e3ee31bf49d.png)
![image](https://user-images.githubusercontent.com/140930/39083921-e223cd0e-453a-11e8-8ce5-06ec7f7c9de8.png)

```
Warning: 'react' peer dependency missing. Run `npm ls` in /Users/pnore/dev/react/gl-react/examples/cookbook-expo to see full warning.
Warning: Installed version 2.4.2 of 'seedrandom' does not satisfy required version github:gre/seedrandom#released

If there is an issue running your project, please run `npm install` in /Users/pnore/dev/react/gl-react/examples/cookbook-expo and restart.
```

#### library version

`$ yarn list --depth=0 --pattern="react|gl|expo" > yarn-list.txt`: [yarn-list.txt](https://github.com/gre/gl-react/files/1934674/yarn-list.txt)

Mac 10.12.5 Sierra

#### Steps to reproduce the behavior
```
git clone https://github.com/gre/gl-react.git
cd gl-react/examples/cookbook-expo/
yarn install
```
Expo IDE --> open project
* gear icon: host: localhost
* device --> iOS Simulator

**Comment by gre** [comment]
latest version should be fixed
