### ISSUE TITLE
Add example with scaled images at different positions

### ISSUE THREAD

**Issue by codekiln** [gre/gl-react#183]
### Example Request: Bouncing Scaled Images

I would like to see an example of using gl-react to scale and translate images, similar to the [WebGLFundamentals Bouncing Image demo](https://webglfundamentals.org/webgl/lessons/webgl-2d-drawimage.html). As a beginner with GLSL, it's unclear to me how to translate this into gl-react. For example, it seems like functions like [m4.translation](https://twgljs.org/docs/module-twgl_m4.html#.translation), [m4.scaling](https://twgljs.org/docs/module-twgl_m4.html#.scaling) would be very helpful, but I'm uncertain whether it makes sense to implement them myself in GLSL, or whether there is a way to use an existing library to get this functionality.

**Comment by gre** [comment]
You can use gl-react-image for this: https://github.com/gre/gl-react-image
and the example is quite explicit: https://gl-react-image.surge.sh/
