### ISSUE TITLE
Surface not show everything

### ISSUE THREAD

**Issue by hoangphuong** [gre/gl-react#185]
### _feature request_?

# -- OR --

### _bug report_?
I have some code:
```
...
import { Surface, GLImage, Negative, Blur} from 'gl-react-native';
...
render() {
      return (
      <Surface width={200} height={100} backgroundColor={'red'}>
               <Blur factor={2}>
                 <Negative>
                   https://i.imgur.com/wxqlQkh.jpg
                 </Negative> 
               </Blur>
             </Surface>
      )
  }
```
#### library version

```bash
npm ls gl-react gl-react-dom gl-react-native gl-react-expo # Please run and paste the output of this
```
├── gl-react@3.15.0 
├── gl-react-expo@3.16.3 
└── gl-react-native@3.15.0 

#### Expected behavior
It's not show anything.
#### Actual behavior
Can you help me got it?

**Comment by gre** [comment]
for react-native there is no such width and height on Surface, you should directly use `style={{ width, height }}`

**Comment by gre** [comment]
this feature is currently not possible. Expo implementation have it and as soon as we merge it back we should have it

**Comment by hoangphuong** [comment]
Thank's, I rollbacked to v2 and it works for me.
