### ISSUE TITLE
shaders turn black when resumes the app after minimizing

### ISSUE THREAD

**Issue by aaeronn** [gre/gl-react#187]
At first render my shader is working perfectly but when I minimize the app or press the home button and reopen the app my shader turns black. 

I am not able to figure out the issue. Do anyone have any idea about it ?
Except this my shader and surface works fine.

**Comment by aaeronn** [comment]
Using react-native

**Comment by raideltorres** [comment]
same for me, using `gl-react-native`

I was using `gl-react-expo` with something like this

```<Surface style={{ width: 335, height: 100 }}>
    <ColorBlending
        color={Colors.cardMask}
        blendMode="blendMultiply"
    >
        {{ uri: 'https://i.imgur.com/iPKTONG.jpg' }}
    </ColorBlending>
</Surface>```

and it was working fine, but I needed to change to `gl-react-native` and now some times it appears black, sometimes white and some times it appears correct as it should.

BTW, the ColorBlending is coming from `gl-react-color-blending` if someone could point me the right way to create a background with blend mode only using `gl-react-native` that will be nice

**Comment by gre** [comment]
probably more relevant to raise this on react-native-webgl. 
it's up to react-native-webgl to sync to latest codebase of expo gl implementation now (not much about gl-react-native)

I have not much time to work on react-native-webgl , hope more maintainers from react-community could help

**Comment by gre** [comment]
Please try with latest version (v4) because I think it's fixed.
