### ISSUE TITLE
App crash with surface inside a flat list

### ISSUE THREAD

**Issue by raideltorres** [gre/gl-react#188]
#### library version

gl-react@3.15.0
gl-react-expo@3.16.3 

#### Expected behavior

It should not crash

#### Actual behavior

The entire app is crashing after scrolling enough

#### Steps to reproduce the behavior

I have something like this:

`<FlatList
    data={stores}
    horizontal={true}
    renderItem={({item}) => {
        return <SmallCard navigation={this.props.navigation} store={item} index={item.key} />
    }}
/>`

and that Card is something like this

`
<Surface style={{ width: 130, height: 100 }}>
    <Colorify colorScale={blendColor} interpolation={'linear'}>
         {{ uri: 'https://i.imgur.com/iPKTONG.jpg' }}
    </Colorify>
</Surface>
`

The stores object is kind of big, like 200-300 items, so after slide a bit the app froze for a second trying to load the Colorify and crash

**Comment by gre** [comment]
Please try again on latest version because I think this is fixed with the v4.
