### ISSUE TITLE
Error When Build in an android device

### ISSUE THREAD

**Issue by nghiata** [gre/gl-react#189]
![error_gl_react_native](https://user-images.githubusercontent.com/13708896/43175167-01c152b0-8fe8-11e8-95e5-c9be0df3368a.PNG)

I have an error when I config in settings.gradle. It said 

> Could not resolve all dependencies for configuration ':app:_debugApk'

> Configuration with name 'default' not found.

This is my settings.gradle

`rootProject.name = 'MyApp'

include ':app'

include ':RNGL'
project(':RNGL').projectDir = file('../node_modules/gl-react-native/android')`

Do I have to comment `include ':app'` ?

**Comment by gre** [comment]
In React Native 0.60, you no longer need to configure this manually so I assume this problem is fixed.
