### ISSUE TITLE
gl-react-headless example

### ISSUE THREAD

**Issue by serhiipalash** [gre/gl-react#192]
Hi @gre!
Can you please provide some example of usage *gl-react-headless*? 
I am working on SSR and I am just interested what is possible to do with it.

**Comment by gre** [comment]
example: https://github.com/gre/gl-transition-libs/tree/master/packages/gl-transition-scripts

**Comment by gre** [comment]
this is currently used by tests:
https://github.com/gre/gl-react/tree/master/packages/tests/__tests__
