### ISSUE TITLE
http and file uri does not render in published EXPO project

### ISSUE THREAD

**Issue by AfflatusX** [gre/gl-react#195]
First of all, thanks for the amazing work around GL!

#### library version

```bash
npm ls gl-react gl-react-dom gl-react-native gl-react-expo # Please run and paste the output of this
```

├── gl-react@3.15.0
└── gl-react-expo@3.16.3

#### Expected behavior

<GLImage source="http://i.imgur.com/tCatS2c.jpg" /> should work for published expo project.

#### Actual behavior

I'm using Expo v29 with gl-react-expo. Everything works fine when testing within Expo iOS client. However, as soon as I publish using exp publish, GLImage stops rendering with any source URI starts with http:// or file:// 

#### Steps to reproduce the behavior

Create a default Expo project using SDK v29, simply render:

```
<Surface style={{ width: '100%', height: 250 }}>
  <GLImage source="http://i.imgur.com/tCatS2c.jpg" />
</Surface>
```

Notice that when running this in dev mode in Expo, it works as expected, but a white screen is shown when the project is published to expo.

Somehow content:// URI (images loaded from camera roll) works fine though.

**Comment by Uniphix** [comment]
I get something very similar.  We are using expo 32, and cannot even get it loaded on the screen either.  And we are using Camera Source URI or Image Library URI. for IOS

**Comment by gre** [comment]
is this still an issue? do you have a minimal example code to reproduce the problem? thanks
