### ISSUE TITLE
Require cycle: gl-react/lib/Bus.js -> gl-react/lib/Node.js -> gl-react/lib/Bus.js

### ISSUE THREAD

**Issue by serhiipalash** [gre/gl-react#199]
Hi @gre !

There is an issue with latest Metro bundler for React Native - it logs warning of `Require cycle` for all node_modules packages

https://github.com/facebook/metro/issues/287

This leads to very slow performance during development in Expo project

https://github.com/expo/expo/issues/2578

Your `gl-react` package also have such warning because of

`Node.js` -> `helpers/invariantNoDependentsLoop.js` -> `Node.js`

<img width="1301" alt="screen shot 2018-11-04 at 12 01 53 pm" src="https://user-images.githubusercontent.com/14208343/47962709-73730980-e029-11e8-8009-4cd37b4acde7.png">

`Bus.js` imports `Node.js` that imports `Bus.js`

<img width="1303" alt="screen shot 2018-11-04 at 12 07 54 pm" src="https://user-images.githubusercontent.com/14208343/47962774-4ecb6180-e02a-11e8-907e-a784ea38027b.png">

Can you please restructure the code to remove this cycle?
I would do it by myself but your code is too complex so I can refactor it and don't break anything.

Steps to reproduce:
```
npm i -g expo-cli
expo init test-require-cycle
cd test-require-cycle
npm install -S gl-react
```
than in `App.js` import `gl-react` 

<img width="1031" alt="screen shot 2018-11-04 at 12 04 52 pm" src="https://user-images.githubusercontent.com/14208343/47962741-f7c58c80-e029-11e8-9933-dfe3e4e11dec.png">

and start the project
```
npm run ios
```
You'll see warnings in Metro logs.

P.S. Here is the same issue fix in `react-native-gesture-handler` package
https://github.com/kmagiera/react-native-gesture-handler/pull/323/files

**Comment by gre** [comment]
I don't think there is this problem anymore?

**Comment by luigbren** [comment]
I have the same problem, I don't know how to solve it

```
Require cycle: node_modules\gl-react\lib\Bus.js -> node_modules\gl-react\lib\Node.js -> node_modules\gl-react\lib\Bus.j
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```
```
Require cycle: node_modules\gl-react\lib\Node.js -> node_modules\gl-react\lib\helpers\invariantNoDependentsLoop.js -> node_modules\gl-react\lib\Node.js
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

appears in the chrome browser when debug mode is active

**Comment by gpbaculio** [comment]
have this problem

**Comment by ajitdas123** [comment]
Same problem even though chrome debugger is off

**Comment by aayush-farmart** [comment]
Hi, this issue is still active on version 5.2.0. Is there any fix for this?
