### ISSUE TITLE
Can I use standard <Image/> to load into the Surface?

### ISSUE THREAD

**Issue by Orxcle-xx** [gre/gl-react#202]
Hi,

Can I use standard `<Image/>` to load into the Surface?
Tried it, doesn't work. Maybe I am doing something wrong. Is it supported?
```
<Surface ...>
   <Image src={....}/>
</Surface>
```

Thank you.

**Comment by gre** [comment]
it's not possible. Surface expects something that renders a `<GL.Node` to be understood. however, checkout https://github.com/gre/gl-react-image
