### ISSUE TITLE
How to enable GLSL extensions like `OES_standard_derivatives`?

### ISSUE THREAD

**Issue by subblue** [gre/gl-react#206]
### Feature
How to enable GLSL extensions like `OES_standard_derivatives`?

#### library version

```bash
├── gl-react@3.15.0
└── gl-react-dom@3.15.0
```

#### Expected behavior
I tried using the `onContextCreate` function of the gl-react-dom Surface which exposes the `gl` instance to enable the extension via `gl.getExtension('OES_standard_derivatives')`

#### Actual behavior
Assigning a custom function to onContextCreate actually silently prevents any rendering from happening!

Is there another way to enable additional WebGL extensions?

Thx

**Comment by brysonandrew** [comment]
+1

**Comment by brysonandrew** [comment]
Hi @subblue 

Had the same issue as yourself.

This worked however:

```
    const gl = ref.glView.canvas.getContext('webgl');
    gl.getExtension('OES_standard_derivatives');
```

With "ref" being the Surface element's ref.

**Comment by subblue** [comment]
Thanks @brysonandrew, good to know that works.
In the end I found a way to do what I needed without the derivatives extension, but good to know for the future 👍

**Comment by brysonandrew** [comment]
Very welcome @subblue sir. Your question helped me find the solution.

**Comment by brysonandrew** [comment]
BTW the above works with `gl-react-dom`

For a Surface from `gl-react-expo`, `onCreateContext` will work.

**Comment by efirdc** [comment]
@brysonandrew Thanks for the tip, but where exactly do you run this code?

I've tried in `componentDidMount()` and the surfaces `preLoad()` but I'm still getting the error that the function is not supported.

**Comment by brysonandrew** [comment]
@efirdc Yes, componentDidMount.

[Here is a gist of the whole component
](https://gist.github.com/brysonandrew/5547a695909005a6c9823b41fab7365f)

Only thing I can think of that you are missing is recording the ref incorrectly...

Also, do you have something like this is your shader -

```
#ifdef GL_OES_standard_derivatives
  #extension GL_OES_standard_derivatives : enable
#endif
```

?
