### ISSUE TITLE
Any simple examples in React?

### ISSUE THREAD

**Issue by ReactGirl** [gre/gl-react#208]
Do we have any simple example how to use the transition this on React App?

The example listed here is not clear how to use:
https://gl-react-cookbook.surge.sh/transitions

I've seen same question asked [here](https://github.com/gre/gl-react/issues/178) but with no response. Is this that hard to have this lib to work in a simple react app?

**Comment by gre** [comment]
https://github.com/gre/gl-transition-libs/blob/master/packages/react-gl-transition/README.md
