### ISSUE TITLE
gl-shader: compiling error android 

### ISSUE THREAD

**Issue by bharatidudhjiya** [gre/gl-react#211]
Library working properly on IOS but issue with android
It is return error like

"gl-shader: Error compiling shader: compile failed."
"Compilation errors. No Code generated."

**library version**
gl-react@3.14.0 
gl-react-native@3.14.0 

Thanks!

**Comment by gre** [comment]
without any GLSL code we can't help

**Comment by farazirfan47** [comment]
@bharatidudhrejiya did you solved the issue?
