### ISSUE TITLE
Module `gl-react/src/isAnimated` does not exist in the Haste module map

### ISSUE THREAD

**Issue by mighty-nyaina** [gre/gl-react#219]
Hi! 
I'm trying to use Surface but got an error. I just import and use it like this

`import { Surface } from "gl-react-native"; `

`<Surface width={300} height={300}></Surface>`

And the error is : 
bundling failed: Error: Unable to resolve module `gl-react/src/isAnimated` from `/Volumes/Macintosh Data/LEARN/AppTest/node_modules/gl-react-native/src/index.js`: Module `gl-react/src/isAnimated` does not exist in the Haste module map

**Comment by gre** [comment]
This means you are not using the correct version of gl-react, you should probably upgrade to v4
