### ISSUE TITLE
how to save image with it's original height and width 

### ISSUE THREAD

**Issue by stepupithubapp** [gre/gl-react#222]
### _feature request_?

# -- OR --

#### library version

```bash
npm ls gl-react gl-react-dom gl-react-native gl-react-expo # Please run and paste the output of this
```

**Comment by gre** [comment]
Use https://github.com/react-native-community/react-native-image-editor to crop/resize an image back to a smaller size.

gl-react will give you the raw image (which respect the pixel ratio), if you need to downscale it, you need such library.
