### ISSUE TITLE
Local image from MediaLibrary can't show on iOS

### ISSUE THREAD

**Issue by maptir** [gre/gl-react#236]
I'm try to implement gl-react to Expo to show a local image that I have. Everything work fines on Android but on iOS when I try to using the 

``` {{ uri: "assets-library://asset/asset.JPG?id=304DF3C0-76AA-4BB2-9387-2626D6FAF44A&ext=JPG'}}``` 

to show image in Node is throw an error like this.

![1132670](https://user-images.githubusercontent.com/25240307/78797009-53473700-79e1-11ea-82f0-d95b02a9aff0.jpg)

More like ``` EXGL:Invalidpixeldataargumentforgl.texImage2D()! ``` in word.

I try to use url that already upload on the internet to show and it's work this happened only when I use local image uri on iOS only.

Thanks.

```
├── gl-react@4.0.1 
├── gl-react-expo@4.0.1 
└── gl-react-native@4.0.1 
```

**Comment by 0plus1** [comment]
I have noticed the same, specifically when updating to Expo SDK38 which in turn updates to React Native 0.62

I have tested this on Android and the same is true there.

**Comment by mistikk** [comment]
same issue

**Comment by obscure723** [comment]
same  issue
when i tried to display local image on iOS, there is black

**Comment by bwoodlt** [comment]
I'm having the same issue... any luck?

**Comment by gre** [comment]
Can you confirm this is now fixed in this upcoming version? Thanks

```
 - gl-react-dom => 5.2.2-next.6+d39872d
 - gl-react-expo => 5.2.2-next.6+d39872d
 - gl-react-headless => 5.2.2-next.6+d39872d
 - gl-react-native => 5.2.2-next.6+d39872d
 - gl-react => 5.2.2-next.6+d39872d
```
