### ISSUE TITLE
Is it possible to handle without uni modulus from expo?

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [gre/gl-react#240]
### _feature request_?
Is it possible to handle without uni modulus from expo?

**Comment by ManigandanRaamanathan** [comment]
@gre

**Comment by gre** [comment]
What do you mean by "handle"?

It used to be relying on react-native-webgl which was its own fork of the expo implementation but it was actually more painful to setup and less maintained so unless you want to fork it on your side there is no alternative today
