### ISSUE TITLE
Surface doesn't render anything.

### ISSUE THREAD

**Issue by risingsunho** [gre/gl-react#243]
When i run code like this
![image](https://user-images.githubusercontent.com/23250874/81905241-6ad89780-95ff-11ea-9a69-56d121bb52ed.png)

It works, but doesn't render anything.

When i run code like this
![image](https://user-images.githubusercontent.com/23250874/81905363-922f6480-95ff-11ea-8dc1-72d6771b9e82.png)

It doesn't work, and App crush.

And, here is my environment

react-native: 0.62.2
buildToolsVersion = "28.0.3"
minSdkVersion = 24
compileSdkVersion = 28
targetSdkVersion = 28
"gl-react": "^4.0.1"
"gl-react-native": "^4.0.1",
"react-native-unimodules": "^0.7.0"

Can you give me a solution?

**Comment by Narinderg** [comment]
Facing same issue. Any fix available?

**Comment by gre** [comment]
Do you have any logs of the crash?

**Comment by gre** [comment]
dup https://github.com/gre/gl-react/issues/242
