### ISSUE TITLE
how to add Text using ViewShot and Surface

### ISSUE THREAD

**Issue by LillyBrainy** [gre/gl-react#247]
`<ViewShot ref='viewShot' style={styles.ViewShot}>
     <TextAnimated style={{color:'red'}}/>
         <Surface style={styles.serface} >
             <Saturate contrast={contrast} saturation={saturation} brightness={brightness}>
                  <BlurV factor={factor} map={map} passes={passes} >
                      <Filter image={imageUri} name={name}  resizeMode={resizeMode} />
                   </BlurV>
              </Saturate> 
         </Surface>
      </ViewShot> 
`when capturing the ViewShot only what inside the. surface is displayed and not the TextAnimated i'm using expo

**Comment by lilyBrainy** [comment]
okay it working fine in ios but in android it ignore the Text and only what inside the surface is displayed

**Comment by gre** [comment]
ViewShot do NOT support snapshotting GL Views.
This is why there is a capture method available on the Surface (if you get a ref of it)

Even tho it might work on iOS there is no guarantee it will continue to, and it also do no work on Android. This is a limitation of ios/android at the moment to not be able to rasterize a gl view.
