### ISSUE TITLE
??

### ISSUE THREAD

**Issue by MuZeQiu** [gre/gl-react#249]
error: Error: Unable to resolve module `buffer` from `node_modules/typedarray-pool/pool.js`: buffer could not be found within the project.

**Comment by luigbren** [comment]
hi my friends.. just install.. buffer..  npm i --save buffer

**Comment by gre** [comment]
Indeed "buffer" as a dependency will solve this. Typically needed in context of Web and React Native. I'm not sure why this error happens in your end tho.
