### ISSUE TITLE
EXGL: Invalid pixel data argument for gl.texImage2D()! When loading images from Firebase on iOS only

### ISSUE THREAD

**Issue by matthewvollmer** [gre/gl-react#256]
#### library version (and associated lib versions)

```bash
├── gl-react@4.0.1 
└─┬ gl-react-native@4.0.1 
  └── gl-react-expo@4.0.1 

└── gl-react-image@3.1.1 

└── react-native@0.62.2 

```

I'm rendering an image inside a surface, with this code:
```
<Surface
  preload={[{uri: this.state.testUri}]}
  style={{
    width:350, 
    height:350}}
    >
  <GLImage
    source={{uri: this.state.testUri}}
    resizeMode='contain'
    imageSize={{width:350, 
      height:350}}
  />
</Surface> 
```
using: 
```
import { Surface } from 'gl-react-native';
import GLImage from "gl-react-image";
```

This works fine on Android for all images. On iOS, it will work okay for some images such as small images hosted in imgur, such as: 
`this.state.testUri = https://i.imgur.com/5EOyTDQ.jpg`

But when trying to load from Firebase, I get this error from "onLoadError" : `EXGL: Invalid pixel data argument for gl.texImage2D()!` and no image will show.

Note: example firebase URL resolves totally fine in a browser, and looks like: 
`https://firebasestorage.googleapis.com/v0/b/<FIREBASE_DATABASE_NAME>/o/<FIREBASE_FILE_LOCATION>.jpg?alt=media&token=<ACCESS_TOKEN>`

These firebase images load just fine in the Surface on Android, and I'm able to load them inside a simple `<Image>` component on iOS (outside of a Surface). Which makes think it's an issue between gl-react's `Surface` and Firebase's encryption. 

Have you seen this error before, or do you have any idea what it means? Is there some sort of limitation with `gl-react` loading images from a protected repo, for iOS only? 

Thank you.

**Comment by LillyBrainy** [comment]
any luck ?

**Comment by jonatasfernandespimenta** [comment]
any updates?

**Comment by gre** [comment]
Is there any testable example / minimal example to reproduce the bug? I don't have a firebase account, i don't know how to test this.

Also I don't think gl-react do anything particular about the way it loads images => it's a topic for Expo assets / GLView probably. maybe except this part https://github.com/gre/webgltexture-loader/blob/master/packages/webgltexture-loader-expo/src/ExpoModuleTextureLoader.js#L42
i would need a minimal case to investigate this (or any contribution is welcomed otherwise)

**Comment by gre** [comment]
Can you confirm this is now fixed in this upcoming version? Thanks

```
 - gl-react-dom => 5.2.2-next.6+d39872d
 - gl-react-expo => 5.2.2-next.6+d39872d
 - gl-react-headless => 5.2.2-next.6+d39872d
 - gl-react-native => 5.2.2-next.6+d39872d
 - gl-react => 5.2.2-next.6+d39872d
```
