### ISSUE TITLE
[Question] Output to video

### ISSUE THREAD

**Issue by gfpacheco** [gre/gl-react#269]
I'm sorry I couldn't find a better place to ask this question, but I hope you could point me in the right direction.

I'm using [react-native-ffmpeg](https://github.com/tanersener/react-native-ffmpeg) to concatenate images and videos into one big video.

Next, I want to add some fancy transitions between them, and found [ffmpeg-gl-transition](https://github.com/transitive-bullshit/ffmpeg-gl-transition) but I couldn't find a build that works on ReactNative (or natively for that matter).

Then I saw this project, and it seems to do everything I want, except it outputs to the screen instead of a video file.

Is there any way to output the render to a video file? Or do you see a way for me to try and make it work?

**Comment by haxakl** [comment]
Hi, i'm on the same problem. Did you find a solution?

**Comment by gre** [comment]
I don't think there is an easy way yet to do this. You might need to go a bit lower level (like write some specific JavaScript code that would do this, as it would need to run "offline" not using React rendering I feel)
