### ISSUE TITLE
React Example to React native example -  WebCam

### ISSUE THREAD

**Issue by K12AZ** [gre/gl-react#276]
### _feature request_?

GL-Webcam example works perfectly, https://gl-react-cookbook.surge.sh/golwebcam?menu=true

Could anyone able to help on react-native example or any idea how we can implement this same feature on react-native way?

Looking forward. 

# -- OR --

#### library version

```bash
+-- gl-react@4.0.1
`-- gl-react-native@4.0.1
  `-- gl-react-expo@4.0.1```

#### Expected behavior

#### Actual behavior

#### Steps to reproduce the behavior

**Comment by gre** [comment]
https://github.com/gre/gl-react/tree/master/examples/expo-gl-react-camera-effects

**Comment by K12AZ** [comment]
Thank you @gre, I need a advice from you. 

import "webgltexture-loader-expo-camera";

Can you use this (webgltexture-loader-expo-camera) library for production level app?

**Comment by gre** [comment]
If it matches your expectation yes. Not sure to understand clearly the question, it can be used in production, but if you experience bad performance you might have to go lower level / try different solutions (native ones). Most of the time, it's "good enough".
