### ISSUE TITLE
Is it possible to use GLSL ES 3.0 with gl-react?

### ISSUE THREAD

**Issue by inokawa** [gre/gl-react#279]
### _feature request_?

I'm not familiar with gl-react and GLSL so I might have mistake...
I heard that If we want to use GLSL ES 3.0 on WebGL, we should write `#version 300 es` at the first line of shader.
However with gl-react, shader name is injected automatically so it seems that I can't write anything at the first line.
Thank you.

#### library version

```bash
├─┬ gl-react-dom@4.0.1
│ └── gl-react@4.0.1 deduped
└── gl-react@4.0.1

```

**Comment by gre** [comment]
Hi.

This would require gl-react to upgrade to WebGL 2.

This is not yet supported but I plan to work on it asap.

**Comment by gre** [comment]
I have some good progress on this. https://twitter.com/greweb/status/1342791717188210694

BTW I just recall myself why the SHADER_NAME was useful: for error traces. but i'll probably try to **append** it instead of prepend. I'll fix this.

**Comment by gre** [comment]
https://github.com/gre/gl-react/releases/tag/v5.0.0

**Comment by inokawa** [comment]
@gre 
Thank you!
