### ISSUE TITLE
CORS issue.. Signed URL (only in uniforms)

### ISSUE THREAD

**Issue by bneigher** [gre/gl-react#293]
Very noob question here.. but for some reason when I use the Shader (created Image Saturate component) I'm getting a CORS exception.  But the image loads fine in a standard img src.  Is there anything specifically that I'm needing here?

I followed this example here:
https://github.com/gre/gl-react/blob/master/packages/cookbook/src/examples/saturation/index.js

Am looking to load a signed url from AWS S3.  I believe it has something to do with the way the image url is passed into the uniforms?

Appreciate any guidance

**Comment by gre** [comment]
https://webglfundamentals.org/webgl/lessons/webgl-cors-permission.html might help
In theory I already did all the measures to load the image tho.
The issue is closed, is the problem fixed?

**Comment by bneigher** [comment]
Indeed this was the problem.  I ended up making the images I need available on the server.  It wasn't a webGL problem as I had issues making ajax calls trying to convert to objectUrls.
