### ISSUE TITLE
TypeError: undefined is not a function (near '...GL.createComponent...')

### ISSUE THREAD

**Issue by Vishal0201** [gre/gl-react#306]
@gre  i installed unimodule and then gl-react 5.0.0 on RN 63.4, after that i am getting this error on iOS and my app is stuck at splash screen. Kindly help !

**Comment by gre** [comment]
`GL.createComponent` does not exist in gl-react 5.0.0. this was an old API from gl-react v2. You don't need this boilerplate anymore, you can use barebone react components.

see documentation https://gl-react-cookbook.surge.sh/api#node
