### ISSUE TITLE
GL is currently not available (have you enabled remote debbuging) shows up on Android

### ISSUE THREAD

**Issue by Vishal0201** [gre/gl-react#335]
### _bug report_?

Hi,
whenever i am trying to load GL with debugging mode on Android it shows up error as GL is currently not available (have you enabled remote debbuging). How to solve it ?

**Comment by gre** [comment]
Unfortunately it is not possible to use debugging mode and GL at the same time due to the way it is implemented (via Expo GLView) https://docs.expo.dev/versions/latest/sdk/gl-view/#remote-debugging--glview
