### ISSUE TITLE
How to load spine animation json file in react-native

### ISSUE THREAD

**Issue by tusharprajapati8888** [gre/gl-react#353]
I have a spine animation JSON file I want to load that in my project.

I found [this](https://medium.com/substantial/animation-in-unity-and-react-native-166d6f069a3c) blog regarding the spine animation.

> Attempts to use middleware animation tools like Spine in combination with React Native were not successful. Spine had many different runtimes but nothing out of the box for RN. We would have had to import WebGL-react-native and glue it together with our own custom tooling.

I am using react native so is there any library/SDK that helps me to load JSON files. Or is this library support in react native if yes what's the step to implement in react native I am not able to find anything regarding react native.

Any help would be highly appreciated.

**Comment by gre** [comment]
sorry but this doesn't feel related to this library.
