### ISSUE TITLE
screenshot any part of the GL tree?

### ISSUE THREAD

**Issue by gre** [gre/gl-react#57]

**Comment by sscaff1** [comment]
Any updates?

**Comment by gre** [comment]
that's definitely planned. in term of priority we might work on https://github.com/ProjectSeptemberInc/gl-react/issues/27 first, which will be a quite important refactoring to allow caching/backbuffering.
have been busy recently, just got back from NY, very jet lagged, i'll need some time to be fully back on track for OSS ^^ ;)

**Comment by gre** [comment]
This is now solved in gl-react v3 ! It's a complete rewrite.
- see release article: http://greweb.me/2016/12/gl-react-v3/
- see cookbook/api: https://gl-react-cookbook.surge.sh
- gl-react v3 is still in development. (hosted on: http://github.com/gre/gl-react )
- gl-react v2 is still the stable version (hosted on: https://github.com/ProjectSeptemberInc/gl-react )


Relevant example that show this issue is fixed: https://gl-react-cookbook.surge.sh/demodesertcrt , https://gl-react-cookbook.surge.sh/pixeleditor
