### ISSUE TITLE
[gl-react-native] how to upgrade to 3.0.0-alpha1

### ISSUE THREAD

**Issue by gullitmiranda** [gre/gl-react#72]
what is the correct process to upgrade to the gl-react-native@^3.0.0-alpha1?

I identified that the `RNGL` has been replaced by the `exponentGLView`, but the [exponent](https://npmjs.com/package/exponent) package ([exponent-sdk](https://github.com/exponentjs/exponent-sdk)) does not make the installation of the main (https://github.com/exponentjs/exponent) package of the exponent that has the native implementation.

**Comment by gre** [comment]
sorry, I need to make this more clear, but **please don't upgrade to gl-react-native 3.0.0**. It's actually not working.
Our goal is to reach the same level of feature, but it's not the case, please stay on v2 for react native.
gl-react v3 alpha is only ready for the web implementation at the moment.

I was thinking NPM didn't show the -alpha1 as the latest release and I was wrong on this :(

**Comment by gre** [comment]
created the task https://github.com/gre/gl-react/issues/74 . stay on the v2 for now, we'll try to get v3 done asap (help welcomed)
