### ISSUE TITLE
gl-react-native: Implement the same level of feature

### ISSUE THREAD

**Issue by gre** [gre/gl-react#74]
The gl-react-native will rely on the wip implementation of WebGL in React Native started by https://docs.getexponent.com/versions/v11.0.0/sdk/gl-view.html

List of things we wish to solve:

- [x] Support for framebuffers. This is fundamental for gl-react.
- [x] interoperability with React Native Image source prop (basically should support same format as a input for gl.texImage2D)
- [x] The WebGL implementation should be a standalone implementation that we can depend as a library (shouldn't requires you to use Exponent if you just use React Native).
- [ ] interoperability with more "pixel sources" (Video, Camera, ...)

**help welcomed!** (especially on improving the WebGL RN implementation)

**Comment by omeid** [comment]
Does that means gl-react-native will only work within an Exponent app or would there be a way to use it in a simple `react-native` app?

**Comment by gre** [comment]
in the long term, I wish it can be independent and works in a normal react-native app.

**Comment by gre** [comment]
there are many milestone before reaching that, but it's planned in my mind.

**Comment by omeid** [comment]
That is going to be a deal breaker for a lot, as in, majory of react-native developers, exponent is not bad, but lack of Native Modules means a lot of people just can't use it. :(

**Comment by gre** [comment]
as said, I plan to make it independent. at worse it can be basically forking all the code from Exponent lib. it's OSS.

**Comment by superandrew213** [comment]
@gre any updates on this?

**Comment by gre** [comment]
yes, I have succeed porting the Exponent implementation in. but now it's not finished:
- no support for textures yet
- some other funky bug i'll try to fix in the next days

**Comment by jimothyhalpert7** [comment]
@gre So the current `master` version of `cookbook-exp` isn't supposed to work?
When i currently run a fresh install I get `EXGL: getParameter() doesn't support g.lFRAMEBUFFER_BINDING yet!`

**Comment by superandrew213** [comment]
Thank you for the update @gre

**Comment by gre** [comment]
@jimothyhalpert7 it should work, but maybe it needs latest exponent?

**Comment by jimothyhalpert7** [comment]
@gre I've upgraded to v14, still getting the same. If I dismiss the issue, the next one says `Surface can only contains a single root. Got: Node#1(copy#1)`.

**Comment by gre** [comment]
we figured it out (sorry for latence) & released a `3.0.0-alpha.4` that should work for gl-react-exponent (still experimental) – make sure you use the same gl-react version

**Comment by gre** [comment]
**note to myself:**

current texture support: exponent only support "local asset images" and RN support none.

my next milestone for RN implementation, trying this idea:

- [ ] from the exgl c++ implementation, calling some interface, that will call the underlying RN Image, e.g. iOS’  `_bridge.imageLoader loadImageWithURLRequest` to reuse the same image code & support the same format of the `Image source` prop. Things needs to be "ready" in sync for the GL impl, so might need to have a `Map` that hold the objs if it's not in RN. Also obviously will need a call to `load` in that Map, hidden by the `*Loader` logic.

if it makes sense, could be backported to Exponent, unless Exponent implement it there own way (which might be transparent for `gl-react-*` user as we can hide this behind the `*Loaders` anyway)

**Comment by superandrew213** [comment]
Great work @gre. Just adding the update you mentioned on the other issue here:

> Concerning the "native" implementation now:
> 
> the RN implementation has been ported out of the EXGL implementation, so we have the same level of feature of the Exponent version at the moment, which is almost everything except the texture support (the complex part).
> 
> For textures:
> 
> The Exponent only have implemented support of Exponent Local Image Asset AND pixels TypedArray.
> For the RN "standalone" implementation: I'm working on it right now and I have just figure out how to make image textures working (not only local images but distant images as well – it supports same format of Image#source prop). I already have the iOS version running here, about to be committed :)
>
> For the rest:
>
> I'll continue to implement the rest of the features and stabilizing what I can see. The v3 is more ambitious in that it use a real implementation of WebGL stack (most of gl methods are there) which means "normal WebGL code" can be written and it will work: gl-react share a lot of WebGL code, gl-react-native don't have much JS except connecting the parts (bridge to GLNativeView, texture loaders,..).
> The native side therefore implement this WebGL abstraction, and it's done in C++ so it's actually shared across Android and iOS!

**Comment by gre** [comment]
https://github.com/gre/gl-react/commit/436e468b6f39da6cd93e3e39c303c018801f237c

**Comment by gre** [comment]
I'm postponing the task `interoperability with more "pixel sources" (Video, Camera, ...)`  to be solved later. It's not blocking to have a first release out.
I'll need to continue polishing things, see `TODO` file in `packages/gl-react-native/` for remaining micro tasks.
