### ISSUE TITLE
Video is blank until lose+restore GL context

### ISSUE THREAD

**Issue by jrmooring** [gre/gl-react#84]
### *bug report*

Using latest Chrome on Windows --

Video tag results in blank image, as on https://gl-react-cookbook.surge.sh/video unless a lose+restore GL context is applied in the inspect window.

Same result with Video wrapping WebCamSource as in https://gl-react-cookbook.surge.sh/blurvideo

https://gl-react-cookbook.surge.sh/blurvideo works, with a slight jitter in the beginning.

**Comment by gre** [comment]
Thanks for the report, I can confirm the problem, I'll get it fixed shortly.

**Comment by jrmooring** [comment]
You rock man! Thanks a bunch. Fantastic project -- really looking forwards to camera support in gl-react-native!
