### ISSUE TITLE
Just a shoutout.

### ISSUE THREAD

**Issue by olofd** [gre/gl-react#86]
@gre  Just wanted to let you know that your doing awesome work with this library!
It really enriches the RN-community. 

I haven't tried v3 yet but looking forward to it! As others I hope that this will run both in Expo (Exponent) and on pure RN.

Just wanted to say, great work! 

You can close when you have read this.

**Comment by gre** [comment]
Thanks for the feedback.

## Here is a little status update:

- The v3 web implementation is ready and well tested, the API itself is ready to go, bring much feature that the limited v2 approach. (examples & docs can be found on https://gl-react-cookbook.surge.sh ).

**Concerning the "native" implementation now:**

the RN implementation has been ported out of the EXGL implementation, so we have the same level of feature of the Exponent version at the moment, which is almost everything except the texture support (the complex part).

**For textures:**
- The Exponent only have implemented support of Exponent Local Image Asset AND pixels TypedArray.
- For the RN "standalone" implementation: I'm working on it right now and I have just figure out how to make image textures working (not only local images but distant images as well – it supports same format of `Image#source` prop).

**For the rest:**
I'll continue to implement the rest of the features and stabilizing what I can see. The v3 is more ambitious in that it's a real implementation of WebGL stack (most of gl methods are there) which means "normal WebGL code" can be written and it will work: gl-react share a lot of WebGL code, gl-react-native don't have much JS except connecting the parts (bridge to GLNativeView, texture loaders,..).
The native side therefore implement this WebGL abstraction, and it's done in C++ so it's actually shared across Android and iOS!

> Note for this WebGL implementation to work, it must run in JavascriptCore, which means the downside is you won't be able to debug it in Chrome debugging mode (your app is still debuggable, but the gl-react view won't render anything). *I wish this was avoidable, but I don't see how it can, the Chrome Debugging is a hack that makes the JS not executing in the app itself but executed async in Chrome, and the WebGL abstraction needs to be sync.*
