### ISSUE TITLE
GL.Node elements can only be used as children of GL.Surface / GL.Node and should not be rendered

### ISSUE THREAD

**Issue by namestise** [gre/gl-react#91]
### *bug report*?

I'm getting `GL.Node elements can only be used as children of GL.Surface / GL.Node and should not be rendered` when implementing https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/example/src/Simple/Saturation.js

#### library version

```bash
"gl-react": "^2.2.10",
"gl-react-native": "^2.42.2",
```

#### Steps to reproduce the behavior

**Comment by gre** [comment]
that means you are trying to render a `<Node>` outside from within a `<Surface>`.  for instance `<View> <Node .. /> </View>` triggers this error )


You need to wrap your Node in a `<Surface ...>`

for instance

```
<View>
  ...
  <Surface ...>
    <Node ... />
  </Surface>
</View>
```

**Comment by gre** [comment]
Node does not produces any rendering on it's own. Only the Surface is the actual pixel area where you render the Node passed as children.

**Comment by gre** [comment]
if one component renders a Node, like this Saturation component, then you need to wrap it in a Surface as well. Surface is the final way to say to react "render!" and it's to be done on user side.

```js
<Surface ...>
  <Saturation ... />
</Surface>
```

**Comment by Dolla123** [comment]
Hello Every one, I am using the following code to crop my image:
```
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import {ImageCrop} from 'react-native-image-cropper'
import { Surface } from 'gl-react-expo';
import ImageFilters from 'react-native-gl-image-filters';

export default class App extends React.Component {
  state={
    height:200,
    width:200,
    image:''
  };

  capture=()=>{
    console.log("hello")
};


  render(){
    return (
   <View>
    <Surface style={{ width:300, height: 300}} ref={ref => (this.image = ref)}>
     <ImageCrop 
      cropHeight={this.state.height}
      cropWidth={this.state.width}
      zoom={1}
      maxZoom={80}
      minZoom={20}
      panToMove={true}
      pinchToZoom={true}
    >
    {{uri: 'https://demo.plugins360.com/wp-content/uploads/2017/12/demo.png'}}
    </ImageCrop>
   </Surface>
    <Text onPress={()=>this.capture()}>Capture()</Text>
  </View>
  );
}
}
```

But this doesnot work, throws this error:

`GL.Node elements can only be used as children of GL.Surface / GL.Node and should not be rendered`

my package.json is:

```
{
  "dependencies": {
    "react-native-paper": "3.6.0",
    "expo-image-cropper-gl-react": "1.1.1",
    "gl-react": "^4.0.1",
    "gl-react-dom": "4.0.1",
    "gl-react-expo": "^4.0.1",
    "gl-react-native": "^4.0.1",
    "react-native-gl-image-filters": "0.2.2",
    "rect-clamp": "^0.0.0",
    "react-native-image-cropper": "0.4.5"
  }
}
```

Please help. this is urgent.
