### ISSUE TITLE
Bad quality of image in Node/Surface

### ISSUE THREAD

**Issue by kesha-antonov** [gre/gl-react#92]
Hello, @gre !

#### gl-react/next + gl-react-native/next

```bash
cookbookrn@0.0.1
├── gl-react@3.0.0-alpha.6 
└── gl-react-native@3.0.0-alpha.6
```

#### Expected behavior

Asset has good quality (as if I put it in ```<Image />```)

#### Actual behavior

Bad quality - blurry image

#### Steps to reproduce the behavior

Download cookbook-rn, run example "Saturation".

----

Original image:

![utp9xfr](https://cloud.githubusercontent.com/assets/11584712/24599076/3a2e029c-1857-11e7-954a-62b6cd85bf2f.jpg)

Left - image in the app
Right - original image in Preview
<img width="678" alt="screen shot 2017-04-03 at 10 16 55" src="https://cloud.githubusercontent.com/assets/11584712/24599091/4b81f1ca-1857-11e7-965f-3f45d3387b8b.png">

Is it possible to improve quality of image in ```Surface```?

**Comment by kesha-antonov** [comment]
I see this problem on in react-native. In browser it looks OK.

<img width="1079" alt="screen shot 2017-04-03 at 12 42 48" src="https://cloud.githubusercontent.com/assets/11584712/24603854/23e462d8-186b-11e7-9b15-8adbe37016af.png">

**Comment by kesha-antonov** [comment]
Hello!

Maybe you could give some advices so I can dig on my own for now?

**Comment by gre** [comment]
thanks for the report.

mmh I'm not sure why this happen.

We need to log out some dimensions to see what's wrong. (e.g. the surface dimension, the actual pixel dimension, the image dimension allocated, ..)

I'll try to investigate that tonight.

**Comment by kesha-antonov** [comment]
Thank you!

**Comment by gre** [comment]
can you tel me if you run that on Simulator and if you have tested on the Phone?

**Comment by kesha-antonov** [comment]
@gre I tried both.
iPhone 5s - simulator and real device

**Comment by kesha-antonov** [comment]
Hello @gre !
Have you had time for this issue?

**Comment by kesha-antonov** [comment]
@gre 
Or maybe you can give me some links where I can find information and try to solve it on my own?
Since OpenGL is whole new world for me I don't know what "to search" :)

I'll try to log dimensions as you suggested for now.

**Comment by kesha-antonov** [comment]
I've tried to set different dimensions in "style" of "Surface". No luck.

Also tried to change width in https://gl-react-cookbook.surge.sh/saturation
The image becomes blurred if I change "480px" -> "481px"

**Comment by gre** [comment]
I can reproduce this. sorry I'm not really sure where to look at, need investigation. it might be a bug before the image get uploaded, or a bug in how we use opengl (like the linear interpolation used, or seomthing)

i'm starting some investigation right now

**Comment by gre** [comment]
ok, so the bug is that the GL View simply don't have the correct size. it still have the pixelRatio=1 instead of retina, mmh. @nikki93 Didn't we fix that recently?
When I log the `gl.drawingBuffer{Width,Height}` it's `375,234` (which is the point size too, so pixel ratio = 1)
same when i log in `resizeViewBuffersToWidth`, it appears that realWidth==width , realHeight==height in there, which I guess should not be true as (iPhone6) simulator is retina.

i'll try to continue investigate this afternoon

**Comment by kesha-antonov** [comment]
Good news.
Thank you for looking at this!

**Comment by gre** [comment]
@nikki93 can you acknowledge that commit above^
it looks like the View was not properly initializing the contentScaleFactor. I used to do that in gl-react-native v2 impl as well.

**Comment by gre** [comment]
I have not tested yet if Android was affected by that but likely not

**Comment by nikki93** [comment]
Oh interesting @gre does this fix the blurrines issue? I did the multisample code based on Ejecta, good catch that I may have missed the buffer sizing.

**Comment by gre** [comment]
yeah this fixes it
<img width="487" alt="screen shot 2017-04-10 at 15 20 40" src="https://cloud.githubusercontent.com/assets/211411/24864001/371a392a-1e03-11e7-9d13-302fa567304b.png">

I'm not yet sure to understand what does the code of the msaa stuff

**Comment by nikki93** [comment]
Awesome!!! Yeah the MSAA code makes a separate framebuffer and does https://www.khronos.org/registry/OpenGL/extensions/APPLE/APPLE_framebuffer_multisample.txt on it. We can't use `GLView` I think and need a custom framebuffer cuz `GLView` doesn't support `readPixels(...)`.

**Comment by gre** [comment]
oh ok

**Comment by kesha-antonov** [comment]
@gre Ah! That was so simple!
Thank you, man! You are awesome!

**Comment by AlishahSolanki** [comment]
@kesha-antonov @gre @nikki93 

i am also trying to implement  something like that but issue is that it capture image with 2x of size of surface size which  is (460x300) in iPhone 11 simulator  and actual size is (3000x2000)

i need image back with actual size after applying filter.
