### ISSUE TITLE
Can't load network images in gl-react-expo package.

### ISSUE THREAD

**Issue by tleef** [gre/gl-react#94]
### *feature request*

Ability to load network images in gl-react-expo package.

The `ExponentTextureLoader` only supports loading using a RN module number. It doesn't support other image sources such as remote or local/cached files using a format similar to `{ uri: 'https://...' }` or `{ uri: 'file:///...' }`

I'm guessing that you've already run into this issue since your `cookbook-rn` examples that use network images such as `transitions` use static images in the `cookbook-expo` version. 

Is there a possible workaround for this? I've considered creating my own `TextureLoader` that loads an `ImageSource`. It would be exactly the same as the `ExponentTextureLoader` except [this line](https://github.com/gre/gl-react/blob/master/packages/gl-react-expo/src/ExponentTextureLoader.js#L26). That logic would change to use `Expo.Asset.fromModule(...)` if the `ImageSource` is a number (the same as it already does) or construct an `Expo.Asset` manually if it is a network image. I would then use `TextureLoaders` to remove the `ExponentTextureLoader` and add my own. I haven't tried this yet but if it works and you are okay with this solution, I'll make a PR for the `ExponentTextureLoader`

#### library version

gl-react@3.0.0-alpha.6
gl-react-expo@3.0.0-alpha.6

**Comment by gre** [comment]
Yeah I don't think Exponent GLView currently have implemented the distant images support BUT as far as I remember @nikki93 told me, you should be able to download the asset to local and use that downloaded asset as URI. I have not tested that tho.

Technically, if Exponent GLView could implement the same 'GLImages' I did for my gl-react-native fork impl, it would support any ImageSource (since i'm reusing the image loader logic from React Native).

**Comment by gre** [comment]
I've released a 3.1.0 that supports remote images by downloading them to a local asset. this is a temporary solution as EXGLView implementation will soon provide a nicer way to handle that :)

**Comment by chachasikes** [comment]
In case anyone is on a hunt to figure out the correct syntax to load an image from a url based on the gl-react-cookbook examples... I finally loaded an image using this syntax & v 3.6.0 of gl-react:

ex: https://github.com/gre/gl-react/blob/master/packages/cookbook/src/examples/saturation/index.js

    <Surface style={styles.displayShader}>
      <Saturate {...this.props}>
        {{uri: 'https://i.imgur.com/uTP9Xfr.jpg'}}
      </Saturate>
    </Surface>

--- 
(though, unfortunately, using a uri value from CameraRoll (...assets-library://) still causes 'the callback downloadAsync() exists in ExponentFileSystem, but only one callback may be registered to a function in a native module') ... still researching the situation, but am still researching / searching through the expo-developers Slack channel for clues... will post if i ever have any success

**Comment by wcandillon** [comment]
Thank you @chachasikes :) You saved me a tremendous amount of time.

**Comment by yedeba** [comment]
Thank you.
something new?,
I can not load yet uri local value (file://data/data...) from camera.
IOS work but not in android.
:(
