### ISSUE TITLE
Handling Text Caption and truncating

### ISSUE THREAD

**Issue by adomrockie** [gre/gl-react#95]
### *feature request*?  Yes

Hey guys, great project you guys are working on, I will want to replace my imagemagick commands functions with this application.

Unfortunately, running a demo myself, it seems it cannot handle text truncating properly. Ideally, I want my text to auto fit or shrink to a given dimension. Will this be something you guys can consider?
# -- OR -- 

#### library version

```bash
npm ls gl-react gl-react-dom gl-react-native gl-react-expo # Please run and paste the output of this
```

**Comment by gre** [comment]
I don't understand your issue. gl-react does not support text, does it?

**Comment by rockyasante** [comment]
I wanted to replace our memegenerator script with gl-react. If gl-react does not handle text overlays then sorry, completely missed what is supposed to do.

**Comment by gre** [comment]
For text, you will have to "rasterize it". We have examples that do this but only on the web implementation (you want for web or react-native ?)

see https://gl-react-cookbook.surge.sh/blurimgtitle

(or just https://gl-react-cookbook.surge.sh/textfunky for a simpler example)

**Comment by gre** [comment]
for react-native it's still possible, you can snapshot a `<Text>` (via react-native-view-shot) and give that image to gl-react

**Comment by rockyasante** [comment]
Thanks , it looks like the question is not for gl-react, an example is https://www.imagemagick.org/Usage/text/#caption_bestfit

**Comment by gre** [comment]
Yeah I think it's a bit out of scope of gl-react at the moment. based on what you need (web or react-native?) it would be other lib responsability to provide such Text caption fit & rasterizing it to an image.

**Comment by rockyasante** [comment]
Thanks so much for gl-react anyway.
